name: Deploy WordPress Theme

on:
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0  # Check for the latest version
        with:
          server: ${{ ftp.typeofsnake.com }}
          username: ${{ snake_theme@theme.typeofsnake.com }}
          password: ${{ Sum@n7274726 }}
          local-dir: ./type-of-snake/  # Ensure this directory exists
          server-dir: /home/seotag5/theme.typeofsnake.com/wp-content/themes/type-of-snake  # Correct input name

      - name: Clear WordPress Cache (Optional)
        run: |
          curl -X POST https://theme.typeofsnake.com/wp-admin/admin-ajax.php?action=clear_cache
